### ISSUE TITLE
## 站点页面动态适配，网页两边留白太多；

### ISSUE THREAD

**Issue by Hamsterwe** [HHANCLUB/Issues#11]
![2](https://user-images.githubusercontent.com/124116916/218009089-9526022e-9e92-4fca-b89e-e05115bd5787.png)
![1](https://user-images.githubusercontent.com/124116916/218009078-b867db8e-38d5-43b6-a03e-566575b41cbe.png)

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，可以附带相关链接

**Comment by baozaodetudou** [comment]
属于UI重构范畴
